"""
Django settings for MAMMOFT_inventory_1_0 project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h__5=bzt351e*a!aw=1_jdter1d@3w23t*f(473ks+^1gl4#@z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#EMAIL_HOST='mail.agroganadero.com.co'
EMAIL_HOST='smtp.gmail.com'
#EMAIL_HOST_USER='sistemas@agroganadero.com.co'
EMAIL_HOST_USER='mammoft@gmail.com'
#EMAIL_HOST_PASSWORD='987654321'
EMAIL_HOST_PASSWORD='94020616866'
EMAIL_PORT=465
EMAIL_USE_SSL='True'

# Application definition

INSTALLED_APPS = (
    'app.login',
    'app.gestion_sistema',
    'app.numeracion_documentos',
    'app.parametrizacion_documentos',
    'app.periodos_contables',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'MAMMOFT_inventory_1_0.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MAMMOFT_inventory_1_0.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':'INVENTORY_MANAGEMENT',
        'USER':'postgres',
        'PASSWORD':'kabala_script',
        'HOST':'localhost',
        'PORT':'',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/


LANGUAGE_CODE = 'es-Col'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfile","static_root")
STATICFILES_DIRS=( os.path.join(BASE_DIR, "staticfile","staticfile_dirs"),
)

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR, "staticfile","media_root")


CRISPY_TEMPLATE_PACK = 'bootstrap3'
